a = int(input("Number of pages:"))
range_ = list(range(1,a+1,2))
from tkinter import Tk
r = Tk()
r.withdraw()
r.clipboard_clear()
range_ = ", ".join(map(str,range_))
r.clipboard_append(range_)
r.update()
input(f"{range_} coppied to clippboard\nPress any key to next range")
range_ = list(range(2,a+1,2))
range_ = ", ".join(map(str,range_))
r.clipboard_clear()
r.clipboard_append(range_)
r.update()
input(f"{range_} coppied to clippboard\nPress any key to exit")
r.destroy()
